-- phpMyAdmin SQL Dump
-- version 5.0.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3307
-- Generation Time: Mar 24, 2020 at 12:03 PM
-- Server version: 10.4.11-MariaDB
-- PHP Version: 7.2.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `quizdb`
--

-- --------------------------------------------------------

--
-- Table structure for table `answers`
--

CREATE TABLE `answers` (
  `aid` int(55) NOT NULL,
  `answer` varchar(250) DEFAULT NULL,
  `ans_id` int(55) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `answers`
--

INSERT INTO `answers` (`aid`, `answer`, `ans_id`) VALUES
(1, '“break” or \"continue\" can be used in “for”, “while” and “do-while” loop body.\r\n', 1),
(2, '“break” and “continue” can be used in “for”, “while” and “do-while” loop body. Besides, “continue” and “break” can be used in “switch” and “if-else” body. \r\n', 1),
(3, '“break” and “continue” can be used in “for”, “while”, “do-while” loop body and “switch” body.', 1),
(4, '“break” and “continue” can be used in “for”, “while” and “do-while” loop body. But only “break” can be used in “switch” body.', 1),
(5, '“unsigned long long int” is a valid data type.', 2),
(6, '“long long double” is a valid data type.', 2),
(7, '“unsigned long double” is a valid data type.', 2),
(8, 'all are valid data types.', 2),
(9, 'all are invalid data types.', 2),
(10, '(float)1.414', 3),
(11, 'float(1.414)\r\n\r\n\r\n', 3),
(12, '1.414f or 1.414F', 3),
(13, '1.414 itself of “float” data type i.e. nothing else required.', 3),
(14, '| and & \r\n\r\n\r\n\r\n', 4),
(15, '&& and || ', 4),
(16, '& and | ', 4),
(17, '|| and && ', 4),
(18, 'JAVA', 5),
(19, 'PHP', 5),
(20, 'C', 5),
(21, 'Visual Basic', 5),
(22, '#include<stdio.h>', 6),
(23, 'return 0', 6),
(24, 'void main(int argc , char ** argy) ', 6),
(25, 'None of above', 6),
(26, 'fputs() with FILE stream as stdout. ', 7),
(27, 'fprintf() with FILE stream as stdout. ', 7),
(28, 'fwrite() with FILE stream as stdout. ', 7),
(29, 'In “stdio.h”, there’s no other equivalent function of printf().', 7),
(30, 'Only int can be used in “switch” control expression. ', 8),
(31, 'Both int and char can be used in “switch” control expression. ', 8),
(32, 'All types i.e. int, char and float can be used in “switch” control expression. ', 8),
(33, '“switch” control expression can be empty as well. ', 8),
(34, ' gcc -o poornimaexamination', 9),
(35, 'gcc -c poornimaexamination', 9),
(36, 'gcc -e poornimaexamination', 9),
(37, 'gcc poornimaexamination', 9),
(38, 'TRUE', 10),
(39, 'FALSE', 10),
(40, 'a>b ? : ; is valid statement i.e. 2nd and 3rd operands can be empty and they are implicitly replaced with non-zero value at run-time. \r\n', 11),
(41, 'a>b ? c=10 : d=10; is valid statement. Based on the value of a and b, either c or d gets assigned the value of 10. \r\n', 11),
(42, 'a>b ? (c=10,d=20) : (c=20,d=10); is valid statement. Based on the value of a and b, either c=10,d=20 gets executed or c=20,d=10 gets executed. \r\n', 11),
(43, 'All of the above are valid statements for ternary operator. ', 11),
(44, 'goto', 12),
(45, 'continue', 12),
(46, 'break', 12),
(47, 'return', 12),
(48, 'All of the above.', 12),
(49, 'It converts source code into assembly code', 13),
(50, 'It converts a assembly language program into machine language', 13),
(51, 'It convert code generated by Preprocessor to assembly code', 13),
(52, 'None of the above.', 13),
(53, '1', 14),
(54, '2', 14),
(55, 'No Limit', 14),
(56, 'Depends on Compiler', 14),
(57, 'Operator', 15),
(58, 'Function', 15),
(59, 'Macro', 15),
(60, 'None of these ', 15),
(61, 'mathio.h', 16),
(62, 'math.h', 16),
(63, 'square.h', 16),
(64, 'stdio.h', 16),
(65, 'Yes', 17),
(66, 'No', 17),
(67, 'Depends on Compiler.', 17),
(68, 'Yes but run time error', 17),
(69, 'gcc -W', 18),
(70, 'gcc -w', 18),
(71, 'gcc -Wall', 18),
(72, 'gcc -wall', 18),
(73, 'gcc -g0', 19),
(74, 'gcc -g1', 19),
(75, 'gcc -g', 19),
(76, 'gcc -g3', 19),
(77, 'gcc -g', 20),
(78, 'gcc -e', 20),
(79, 'gcc -a', 20),
(80, 'gcc -b', 20);

-- --------------------------------------------------------

--
-- Table structure for table `contactus`
--

CREATE TABLE `contactus` (
  `id` int(55) NOT NULL,
  `name` varchar(250) NOT NULL,
  `email` varchar(250) NOT NULL,
  `message` text NOT NULL,
  `created_date` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `contactus`
--

INSERT INTO `contactus` (`id`, `name`, `email`, `message`, `created_date`) VALUES
(1, 'Jinesh Nagori', 'jineshn21@gmail.com', 'good website...', '2020-03-24');

-- --------------------------------------------------------

--
-- Table structure for table `questions`
--

CREATE TABLE `questions` (
  `qid` int(55) NOT NULL,
  `question` varchar(250) DEFAULT NULL,
  `ans_id` int(55) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `questions`
--

INSERT INTO `questions` (`qid`, `question`, `ans_id`) VALUES
(1, 'In the context of “break” and “continue” statements in C, pick the best statement.', 4),
(2, 'In the context of C data types, which of the followings is correct?\r\n', 5),
(3, 'Suppose a C program has floating constant 1.414, what’s the best way to convert this as “float” data type?', 12),
(4, 'For a given integer, which of the following operators can be used to “set” and “reset” a particular bit respectively? \r\n', 14),
(5, ' Which programming language is more faster among these?', 20),
(6, ' Which of the following is executed by Preprocess? ', 22),
(7, 'Which of the following functions from “stdio.h” can be used in place of printf()? ', 27),
(8, 'Which of the following statement is correct for switch controlling expression? ', 31),
(9, 'Which command is to compile C code without linking using gcc compiler?', 35),
(10, 'In the below statement, ptr1 and ptr2 are uninitialized pointers to int i.e. they are pointing to some random address that may or may not be valid address. \r\nint* ptr1, ptr2;  \r\n', 39),
(11, 'Suppose a, b, c and d are int variables. For ternary operator in C ( ?: ), pick the best statement. ', 42),
(12, 'Which of the following is correct with respect to “Jump Statements” in C? ', 48),
(13, 'What is the job of Assembler in C programming?', 50),
(14, 'How many main() function we can have in our project?', 53),
(15, 'What is sizeof() in C?', 57),
(16, 'Library function pow() belongs to which header file?', 62),
(17, 'Can we declare function inside structure of C Programming?', 66),
(18, 'Which gcc flag is used to enable all Compiler warnings?', 71),
(19, 'Which gcc flag is used to generate maximum debug information?', 76),
(20, 'Which gcc flag is used to genarate debug information for any binary file?', 77);

-- --------------------------------------------------------

--
-- Table structure for table `quizregistration`
--

CREATE TABLE `quizregistration` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `user` varchar(255) NOT NULL,
  `pass` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `quizregistration`
--

INSERT INTO `quizregistration` (`id`, `name`, `user`, `pass`) VALUES
(1, 'a', 'ad@gmail.com', 'a'),
(2, 'd', 'ad@gmail.com', 's'),
(3, 'Jinesh ', 'jineshn21@gmail.com', 'jinesh'),
(4, 'raja', 'raja@raja', 'raja'),
(5, '', '', ''),
(6, 'root', 'root@gmail.com', '123'),
(7, 'amit', 'amit@gmail.com', '123'),
(8, 'h', 'h@h', 'h'),
(9, 'j', 'j@j', 'j'),
(10, 'lali', 'lali@lali', '123'),
(11, 'Jinesh ', 'hii@hii', '123');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `id` int(250) NOT NULL,
  `username` varchar(250) NOT NULL,
  `totalques` int(250) NOT NULL,
  `correctans` int(250) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `username`, `totalques`, `correctans`) VALUES
(4, 'jineshn21@gmail.com', 0, 0),
(5, 'raja@raja', 0, 0),
(6, 'raja@raja', 0, 0),
(7, 'raja@raja', 0, 0),
(8, 'raja@raja', 0, 0),
(9, 'raja@raja', 0, 0),
(10, 'raja@raja', 0, 0),
(11, 'raja@raja', 0, 0),
(12, 'raja@raja', 0, 0),
(13, 'raja@raja', 0, 0),
(14, 'raja@raja', 0, 0),
(15, 'jineshn21@gmail.com', 0, 0),
(16, 'raja@raja', 0, 0),
(17, 'raja@raja', 0, 0),
(18, 'raja@raja', 0, 0),
(19, 'root@gmail.com', 0, 0),
(20, 'root@gmail.com', 0, 0),
(21, 'root@gmail.com', 0, 0),
(22, 'amit@gmail.com', 0, 0),
(23, 'raja@raja', 0, 0),
(24, 'raja@raja', 0, 0),
(25, 'root@gmail.com', 0, 0),
(27, 'h@h', 0, 0),
(28, 'h@h', 20, 17),
(29, 'h@h', 0, 0),
(30, 'h@h', 20, 4),
(31, 'h@h', 0, 0),
(32, 'h@h', 20, 4),
(33, 'j@j', 0, 0),
(34, 'j@j', 20, 4),
(35, 'raja@raja', 0, 0),
(36, 'raja@raja', 1, 1),
(37, 'lali@lali', 0, 0),
(38, 'lali@lali', 2, 0),
(39, 'lali@lali', 1, 0),
(40, 'hii@hii', 0, 0),
(41, 'hii@hii', 1, 0),
(42, 'raja@raja', 0, 0),
(43, 'raja@raja', 1, 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `contactus`
--
ALTER TABLE `contactus`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `quizregistration`
--
ALTER TABLE `quizregistration`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `id` (`id`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `contactus`
--
ALTER TABLE `contactus`
  MODIFY `id` int(55) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `quizregistration`
--
ALTER TABLE `quizregistration`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `id` int(250) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=44;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
